all: main.o double_linked_list.o showNode.o Import_Export.o showlist.o searchDisplay.o newinsertlist.o showGroup.o
	gcc -o testmain main.o double_linked_list.o showNode.o Import_Export.o showlist.o searchDisplay.o newinsertlist.o showGroup.o
	./testmain